name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run make_release_actions.sh
      run: |
        ./make_release_actions.sh

    - name: Docker Images
      run: |
        docker images

    # - name: Push Docker Image
    #   run: |
    #     docker push ohrafaelmartins/elixirdemo:${GITHUB_SHA}
    #     docker push ohrafaelmartins/elixirdemo:latest
